# Set site parameters
SITE_NAME = 'Network Planner'
SITE_VERSION = '0.9.7'
SITE_DESCRIPTION = 'Network Planning for Rural Electrification'
SITE_KEYWORDS = 'Network planning, rural electrification'
# Set person parameters
EMAIL_LENGTH_MAXIMUM = 48
NICKNAME_LENGTH_MINIMUM = 3
NICKNAME_LENGTH_MAXIMUM = 32
USERNAME_LENGTH_MINIMUM = 6
USERNAME_LENGTH_MAXIMUM = 32
PASSWORD_LENGTH_MINIMUM = 6
PASSWORD_LENGTH_AVERAGE = 16
NICKNAME_LENGTH_MINIMUM = 3
ROLE_LENGTH_MAXIMUM = 16
TICKET_LENGTH = 32
TICKET_LIFESPAN_IN_DAYS = 1
REJECTION_LIMIT = 3
MINUTES_OFFSET_DEFAULT = 240
# Set scenario parameters
SCENARIO_NAME_LENGTH_MAXIMUM = 256
# Set processor parameters
IP_LENGTH_MAXIMUM = 39
# Set job parameters
HOST_LENGTH_MAXIMUM = 64
